### ISSUE TITLE
Game crashes when loading hopper minecart 1.19.4

### ISSUE THREAD

**Issue by Minecatr** [SoGCuicui/Sticky-Hopper#1]
when you load a hopper minecart into the world game crashes

here is the crash report:
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-06-04 17:47:55
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1700 cannot be cast to class net.minecraft.class_2614 (net.minecraft.class_1700 and net.minecraft.class_2614 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @185d8b6)
	at net.minecraft.class_2614.handler$bdd000$stickyhopper$sh_extract_head(class_2614.java:4127)
	at net.minecraft.class_2614.method_11247(class_2614.java)
	at net.minecraft.class_2614.method_11241(class_2614.java:202)
	at net.minecraft.class_1700.method_7574(class_1700.java:95)
	at net.minecraft.class_1700.method_5773(class_1700.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2614.handler$bdd000$stickyhopper$sh_extract_head(class_2614.java:4127)
	at net.minecraft.class_2614.method_11247(class_2614.java)
	at net.minecraft.class_2614.method_11241(class_2614.java:202)
	at net.minecraft.class_1700.method_7574(class_1700.java:95)
	at net.minecraft.class_1700.method_5773(class_1700.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:722)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:hopper_minecart (net.minecraft.class_1700)
	Entity ID: 195
	Entity Name: Minecart with Hopper
	Entity's Exact location: -7559.50, 11.06, 3838.50
	Entity's Block location: World: (-7560,11,3838), Section: (at 8,11,14 in -473,0,239; chunk contains blocks -7568,-64,3824 to -7553,319,3839), Region: (-15,7; contains chunks -480,224 to -449,255, blocks -7680,-64,3584 to -7169,319,4095)
	Entity's Momentum: 2.05, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Minecatr'/168, l='ServerLevel[world]', x=-7559.13, y=73.00, z=3857.66]]
	Chunk stats: 4139
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,85,-64), Section: (at 0,5,0 in -8,5,-4; chunk contains blocks -128,-64,-64 to -113,319,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 34307653 game time, 35716693 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 16195 (now: false), thunder time: 83324 (now: false)
	Known server brands: Fabric/Gunpowder, vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 32123130016 bytes (30635 MiB) / 34359738368 bytes (32768 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75183.49
	Virtual memory used (MB): 59673.03
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 258.96
	JVM Flags: 2 total; -Xms32767M -Xmx32767M
	Fabric Mods: 
		autocrafter: FabricAutoCrafter 1.0.10
			polymer-core: Polymer (Core) 0.4.0+1.19.4
				polymer-networking: Polymer (Networking) 0.4.0+1.19.4
					polymer-common: Polymer (Common) 0.4.0+1.19.4
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.4.0+1.19.4
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 10.0.0.3
		colorfulanvils: Colorful Anvils 1.1.0+1.19.x
			fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
				org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
				org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
				org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
				org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
				org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
				org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
				org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
				org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
				org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
				org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.0+1.19.4
		diamondchestshop: Diamond Chest Shop 1.2.5+1.19.4
		diamondeconomy: Diamond Economy 1.5.6
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
		diamondsauctionhouse: Diamond Auction House 1.1.41.19.3
			sgui: sgui 1.2.1+1.19.3
		fabric-api: Fabric API 0.82.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.1+fe8721bef4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.1+b4a333d6f4
		fabricloader: Fabric Loader 0.14.19
		ferritecore: FerriteCore 5.2.0
		htm: Hey That's Mine 1.1.8
			common-protection-api: Common Protection API 1.0.0
		jade: Jade 10.3.0
		jamlib: JamLib 0.6.0+1.19.4
		java: OpenJDK 64-Bit Server VM 17
		jline4mcdsrv: JLine for Minecraft Dedicated Server 0.4.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			org_fusesource_jansi_jansi: jansi 2.4.0
			org_jline_jline: jline 3.22.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.22.0
		lithium: Lithium 0.11.1
		minecraft: Minecraft 1.19.4
		nochatreports: No Chat Reports 1.19.4-v2.1.3
		reputation: Your Reputation 0.2.1+jade.1.19
		stickyhopper: Sticky Hopper 4.1-ServerSideOnly-1.19.1
		tdnf: Trees Do Not Float 3.0.186
			blue_endless_jankson: jankson 1.2.1
	Server Running: true
	Player Count: 1 / 22; [class_3222['Minecatr'/168, l='ServerLevel[world]', x=-7559.13, y=73.00, z=3857.66]]
	Data Packs: vanilla, file/curse (incompatible), file/VanillaTweaks_c959663.zip (incompatible), file/chunk loaders v1.0.4.zip (incompatible), file/classic fishing loot v1.1.3.zip (incompatible), file/double shulker shells v1.3.3.zip (incompatible), file/elevators v1.0.4.zip (incompatible), file/graves v2.8.6.zip (incompatible), file/larger phantoms v1.2.4.zip (incompatible), file/more mob heads v2.10.0.zip (incompatible), file/villager death messages v1.2.4.zip (incompatible), file/wandering trades v1.5.2.zip (incompatible), file/xp management v1.1.3.zip (incompatible), fabric, file/cauldron concrete v2.0.6.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by Rikyo8** [comment]
man i'm not a developer but i think that's my same issue because the reason of the crash in the ticking entity, if you want a way to enter the server just use "neruina" mod but it is not a fix for the mod

**Comment by Rikyo8** [comment]
let me know if you are able to contact the developer of this mod because i really need this mod
